Social_Nano_Network/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('snn/', include('snn.urls')),
]

snn/urls.py
from django.urls import path, re_path

from . import views

app_name = 'snn'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:user_id>/profile_page', views.profile_page, name='profile_page'),
    path('<int:user_id>/',views.add_remove_friends, name='add_remove_friends'),
    path('<int:user_id>/chat_room',views.chat_room, name='chat_room'),
    re_path(r'^catch_friends/$',views.catch_friends, name='catch_friends'),
    re_path(r'^chats_giver/$',views.chats_giver, name='chats_giver'),
    re_path(r'^chat_fetcher/$',views.chat_fetcher, name='chat_fetcher'),
    re_path(r'^message_sender/$',views.message_sender, name='message_sender'),
    re_path(r'^messages_giver/$',views.messages_giver, name='messages_giver'),
]

snn/models.py
from django.db import models
from django.db.models import Q
import datetime

class Chats(models.Model):
    chat_id = models.AutoField(primary_key=True)
    chat_key = models.IntegerField()
    participant1_id = models.ForeignKey('Users', on_delete=models.CASCADE, related_name='participant1_id')
    participant2_id = models.ForeignKey('Users', on_delete=models.CASCADE, related_name='participant2_id')
    participant1_name = models.CharField(max_length=500)
    participant2_name = models.CharField(max_length=500)
    last_mes_auth_id = models.ForeignKey('Users', on_delete=models.CASCADE, related_name='last_mes_auth_id')
    last_mes_auth_name = models.CharField(max_length=500)
    last_mes_text = models.CharField(max_length=5000)
    last_mes_ts = models.DateTimeField(auto_now=True) #auto_now_add=True

    @staticmethod
    def createChat(mes_info):
    	sender_id = mes_info['sender_id']
    	sender_name = mes_info['sender_name']
    	recipient_id = mes_info['recipient_id']
    	recipient_name = mes_info['recipient_name']
    	message = mes_info['message']
    	key = sender_id + recipient_id
    	chat = Chats(chat_key=key,participant1_id_id=sender_id,participant2_id_id=recipient_id,participant1_name=sender_name,participant2_name=recipient_name,last_mes_auth_id_id=sender_id,last_mes_auth_name=sender_name,last_mes_text=message)
    	chat.save()

    @staticmethod
    def updateChat(mes_info):
    	sender_id = mes_info['sender_id']
    	sender_name = mes_info['sender_name']
    	recipient_id = mes_info['recipient_id']
    	message = mes_info['message']
    	chat = Chats.objects.get(Q(participant1_id_id=sender_id,participant2_id_id=recipient_id) | Q(participant2_id_id=sender_id,participant1_id_id=recipient_id))
    	chat.last_mes_auth_id_id = sender_id
    	chat.last_mes_auth_name = sender_name
    	chat.last_mes_text = message
    	#chat.last_mes_ts = datetime.datetime.now()
    	chat.save()

    @staticmethod
    def fetchMessages(id_1,id_2):
    	chat_raw = Messages.objects.filter(Q(recipient_id_id=id_1,sender_id_id=id_2) | Q(recipient_id_id=id_2,sender_id_id=id_1)).order_by('message_id')
    	chat = []
    	for c in chat_raw:
    		message = {'sender_id':0, 'recipient_id':0, 'sender_name':0, 'message':0}
    		message['sender_id'] = c.sender_id_id
    		message['recipient_id'] = c.recipient_id_id 
    		message['sender_name'] = c.sender_name
    		message['message'] = c.message
    		chat.append(message)
    	return chat


class Friends(models.Model):
    friendship_id = models.AutoField(primary_key=True)
    fr1_id = models.ForeignKey('Users', on_delete=models.CASCADE, related_name='fr1_id')
    fr2_id = models.ForeignKey('Users', on_delete=models.CASCADE, related_name='fr2_id')


class Messages(models.Model):
    message_id = models.AutoField(primary_key=True)
    recipient_id = models.ForeignKey('Users', on_delete=models.CASCADE, related_name='recipient_id')
    recipient_name = models.CharField(max_length=500)
    sender_id = models.ForeignKey('Users', on_delete=models.CASCADE, related_name='sender_id')
    sender_name = models.CharField(max_length=500)
    message = models.CharField(max_length=5000)
    ts = models.DateField()

    @staticmethod
    def postMessage(mes_info):
    	if not mes_info:
    		return
    	sender_id = mes_info['sender_id']
    	sender_name = mes_info['sender_name']
    	recipient_id = mes_info['recipient_id']
    	recipient_name = mes_info['recipient_name']
    	message = mes_info['message']
    	mes = Messages(sender_id_id=sender_id,sender_name=sender_name,recipient_id_id=recipient_id,recipient_name=recipient_name,message=message)
    	mes.save()
    	chat = Chats.objects.filter(Q(participant1_id_id=sender_id,participant2_id_id=recipient_id) | Q(participant2_id_id=sender_id,participant1_id_id=recipient_id))
    	if chat:
    		Chats.updateChat(mes_info)
    	else:
        	Chats.createChat(mes_info)


class Users(models.Model):
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=500)
    password = models.CharField(max_length=500)
    email = models.CharField(max_length=500)

    def __str__(self):
        return 'id %s %s' % (self.user_id, self.username)

    def getOtherMembers(self):
    	members = Users.objects.all().exclude(pk=self.user_id)
    	return members

    def get_fr_IDs(self):
    	fr_IDs = []
    	result = Friends.objects.filter(Q(fr1_id=self.user_id) | Q(fr2_id=self.user_id))
    	for every in result:
            if every.fr1_id_id == self.user_id:
            	fr_IDs.append(every.fr2_id_id)
            else:
            	fr_IDs.append(every.fr1_id_id)
    	return fr_IDs

    def get_fr_info(self):
    	fr_info = []
    	result = Friends.objects.filter(Q(fr1_id=self.user_id) | Q(fr2_id=self.user_id))
    	if result:
    	    for every in result:
                if every.fr1_id_id == self.user_id:
            	    info = {'id':every.fr2_id.user_id, 'name':every.fr2_id.username}
            	    fr_info.append(info)
                else:
            	    info = {'id':every.fr1_id.user_id, 'name':every.fr1_id.username}
            	    fr_info.append(info)
    	return fr_info

    def get_last_friendship_id(self):
    	result = Friends.objects.filter(Q(fr1_id=self.user_id) | Q(fr2_id=self.user_id))
    	if result:
    		n = len(result)
    		last_id = result[n-1].friendship_id
    		return last_id
    	else:
    		return 0

    def addFriend(self,fr_id):
    	fr_IDs = self.get_fr_IDs()
    	fr_id = int(fr_id)
    	if not fr_id in fr_IDs:
    		friendship = Friends(fr1_id_id=self.user_id,fr2_id_id=fr_id)
    		friendship.save()

    def removeFriend(self,fr_id):
    	fr_IDs = self.get_fr_IDs()
    	fr_id = int(fr_id)
    	if fr_id in fr_IDs:
    		friendship = Friends.objects.get(Q(fr1_id=self.user_id,fr2_id=fr_id) | Q(fr2_id=self.user_id,fr1_id=fr_id))
    		friendship.delete()

    def fetch_chats(self):
    	chats_raw = Chats.objects.filter(Q(participant1_id=self.user_id) | Q(participant2_id=self.user_id)).order_by('-last_mes_ts')
    	if chats_raw:
    		chats = []
    		for c in chats_raw:
    			chat = {'partner_id':0, 'partner_name':0, 'last_mes_auth_id':0, 'last_mes_auth_name':0, 'last_mes_text':0, 'last_mes_ts':0}
    			chat['partner_id'] = c.chat_key - self.user_id
    			if c.participant1_id_id == self.user_id:
    				chat['partner_name'] = c.participant2_name
    			else:
    				chat['partner_name'] = c.participant1_name
    			chat['last_mes_auth_id'] = c.last_mes_auth_id_id
    			chat['last_mes_auth_name'] = c.last_mes_auth_name
    			chat['last_mes_text'] = c.last_mes_text
    			chat['last_mes_ts'] = c.last_mes_ts
    			chats.append(chat)
    		return chats

    def get_last_rec_mes_id(self):
    	result = Messages.objects.filter(recipient_id=self.user_id)
    	if result:
    		n = len(result)
    		last_id = result[n-1].message_id
    		return last_id
    	else:
    		return 0

    def fetch_received_messages(self,mes_id):
    	messages_raw = Messages.objects.filter(Q(recipient_id=self.user_id) & Q(message_id__gt=mes_id)).order_by('message_id')
    	if messages_raw:
    		messages = []
    		for m in messages_raw:
    			message = {'message_id':m.message_id, 'sender_id':m.sender_id_id, 'recipient_id':m.recipient_id_id, 'sender_name':m.sender_name, 'message':m.message}
    			messages.append(message)
    		return messages


    	
    	# cd C:\Python\Social_Nano_Network

    	# python manage.py shell

    	# from snn.models import Users,Friends

    	# u = Users.objects.get(pk=1)

    	# u.removeFriend(5)




    

    

snn/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.urls import reverse
from django.template import loader
import json
from django.utils.safestring import mark_safe
from django.db.models import Q
from .models import Users, Friends, Messages, Chats

def index(request):
    pass

def profile_page(request,user_id):
	user = Users.objects.get(pk=user_id)
	username = user.username
	members = user.getOtherMembers()
	fr_IDs = user.get_fr_IDs()
	fr_info = user.get_fr_info()
	last_friendship_id = user.get_last_friendship_id()
	context = {'user_id':user_id, 'username':username, 'members':members, 'fr_IDs':fr_IDs, 'fr_info':fr_info, 'last_friendship_id':last_friendship_id}
	template = loader.get_template('snn/profile_page.html')
	return HttpResponse(template.render(context, request))

def add_remove_friends(request,user_id):
	user = Users.objects.get(pk=user_id)
	if request.POST['action']=='add':
	 	user.addFriend(request.POST['member_id'])
	elif request.POST['action']=='remove':
		user.removeFriend(request.POST['member_id'])
	return HttpResponseRedirect(reverse('snn:profile_page', args=(user_id,)))

def catch_friends(request):
	user_id = int(request.GET.get('user_id'))
	user = Users.objects.get(pk=user_id)
	last_friendship_id_js = int(request.GET.get('id')) 
	last_friendship_id = user.get_last_friendship_id()
	if last_friendship_id != last_friendship_id_js:
		return HttpResponse(last_friendship_id)
	
def chat_room(request,user_id):
	partner_id = request.POST['fr_id']
	partner_name = request.POST['fr_name'] 
	user = Users.objects.get(pk=user_id)
	user_id = user.user_id
	username = user.username
	chats_raw = user.fetch_chats()
	chats = mark_safe(json.dumps(chats_raw, default=str))  
	last_rec_mes_id = user.get_last_rec_mes_id()
	context = {'partner_id':partner_id, 'partner_name':partner_name, 'user_id':user_id, 'username':username, 'chats':chats, 'last_rec_mes_id':last_rec_mes_id}
	template = loader.get_template('snn/chat_room.html')
	return HttpResponse(template.render(context, request))

def chats_giver(request):
	user_id = int(request.GET.get('user_id'))
	user = Users.objects.get(pk=user_id)
	chats_raw = user.fetch_chats()
	chats = mark_safe(json.dumps(chats_raw, default=str))
	return HttpResponse(chats)

def chat_fetcher(request):
	user_id = int(request.GET.get('user_id'))
	partner_id = int(request.GET.get('partner_id'))
	chat_raw = Chats.fetchMessages(user_id,partner_id) 
	chat = mark_safe(json.dumps(chat_raw, default=str))
	return HttpResponse(chat)

def message_sender(request):
	sender_id = int(request.GET.get('user_id'))
	sender_name = request.GET.get('user_name')
	recipient_id = int(request.GET.get('partner_id'))
	recipient = Users.objects.get(pk=recipient_id)
	recipient_name = recipient.username
	message = request.GET.get('message')
	mes_info = {'sender_id':sender_id, 'sender_name':sender_name, 'recipient_id':recipient_id, 'recipient_name':recipient_name, 'message':message}
	Messages.postMessage(mes_info)
	return HttpResponse()

def messages_giver(request):
	user_id = int(request.GET.get('user_id'))
	mes_id = int(request.GET.get('mes_id'))
	user = Users.objects.get(pk=user_id)
	messages_raw = user.fetch_received_messages(mes_id)
	messages = mark_safe(json.dumps(messages_raw, default=str))
	return HttpResponse(messages)

	


snn/templates/snn/chat_room.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>{{username}} chat room</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" charset="UTF-8">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'snn/css/chat_room.css' %}" />
</head>
<body>
	<header>
		<nav class="navbar navbar-default navbar-fixed-top" style="background: linear-gradient(to bottom, #33ccff 0%, #ff99cc 100%); height: 5%;">
		    <div class="container-fluid">
			    <div class="navbar-header">
				    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
					    <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span> 
					</button>
					<a class="navbar-brand" href="{% url 'snn:profile_page' user_id %}">{{username}}</a>
				</div>
				<div class="collapse navbar-collapse" id="myNavbar">
					<ul class="nav navbar-nav navbar-right">
					    <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
    <div class="container-fluid" style="margin-top:50px">
    	<div class="row">
    		<div class="col-sm-3">
    			<div id="chats_wrapper"></div>
    		</div>
    		<div class="col-sm-6" id="mes" style="height: 370px">
    		</div>
    		<div class="col-sm-3" id="sidebar">
                <div style="text-align: center; padding-top:5%">
		            If you would like to chat to someone with whom you do not have an active chat yet, then please go to your profile page by clicking your username in the left uppermost corner of the page, and then select that person from your friend list.
		        </div>
           </div> 
    	</div>
    	<div class="row">
		    <div class="col-sm-6 col-sm-offset-3">
				<textarea class="form-control" rows="4" id="text" form="message" name="message" placeholder="Type your message here:"></textarea>
                <button type="button" class="btn btn-info" onclick="send_message()">Send</button>
		    </div>
	    </div>
    </div>
</body>
<script type="text/javascript">
	var mes_height = $("#mes").outerHeight(); 
	var n; // message counter reflected in message html id
	var id = {{partner_id}};
	var name = "{{partner_name}}";
	var user_id = {{user_id}};
	var user_name = "{{username}}";
	var chats= {{chats}};
	var last_rec_mes_id = {{last_rec_mes_id}};
	var test;

	$(document).ready(form_chats(),display_chat(id,name));

	function form_chat_header(chat) {
		if (chat.partner_id==id) {
			var content = '<div class="active_chat_header" id="c'+chat.partner_id+'" onclick="display_chat('+chat.partner_id+')">'+'<b>'+chat.partner_name+'</b><br>'+chat.last_mes_auth_name+': '+chat.last_mes_text+'</div>';
			$("#chats_wrapper").append(content);
		} else {
			name = chat.partner_name;
			var content = '<div class="chat_header" id="c'+chat.partner_id+'" onclick="display_chat('+chat.partner_id+')">'+'<b>'+chat.partner_name+'</b><br>'+chat.last_mes_auth_name+': '+chat.last_mes_text+'</div>';
			$("#chats_wrapper").append(content);
		}
	}

	function form_chats() {
        $.get('{% url 'snn:chats_giver' %}',{user_id:user_id}, 
        	function(data, status){
                if (status=="success") {
                	chats = JSON.parse(data);
                    $("#chats_wrapper").html('');
                    chats.forEach(form_chat_header);
                }
            }
        );
	}

	function display_message(message) {
		if (message.sender_id==id || message.recipient_id==id) {
			n++;
		    if (message.sender_id == user_id) {
			    var content = '<div class="message_outlet" id="m'+n+'"><b>You:</b> '+message.message+'</div><br>';
			    $("#mes").append(content);
		    } else {
                var content = '<div class="message_inlet" id="m'+n+'"><b>'+message.sender_name+':</b> '+message.message+'</div><br>';
                $("#mes").append(content);
		    }
            var last_mes_pos = document.getElementById("m"+n).offsetTop;
            if (last_mes_pos > mes_height) {
                document.getElementById("mes").scrollTop = last_mes_pos; 
            }
		} else {
			alert("You received new message from "+message.sender_name);
		}
	} 

	function display_chat(partner_id) { 
		n = 0;
	    id = partner_id;  
        $.get('{% url 'snn:chat_fetcher' %}',{user_id:user_id, partner_id:id}, 
        	function(data, status){
                if (status=="success") {
                	$("#mes").html('')
                	var messages = JSON.parse(data);
                    messages.forEach(display_message);
                }
            }
        );
        chats.forEach(function(item){
        	if (item.partner_id==id) {
        		$("#c"+id).attr("class","active_chat_header");
        	} else {
        		$("#c"+item.partner_id).attr("class","chat_header");
        	}
        });
    }

    function send_message() {
        var message = $("#text").val();
        $.get('{% url 'snn:message_sender' %}',{user_id:user_id, user_name:user_name, partner_id:id, message:message}, 
        	function(data, status){
                if (status=="success") {
                	n++;
                	var content = '<div class="message_outlet" id="m'+n+'"><b>You:</b> '+message+'</div><br>';
                	$("#mes").append(content);
                	var last_mes_pos = document.getElementById("m"+n).offsetTop;
                    if (last_mes_pos > mes_height) {
                        document.getElementById("mes").scrollTop = last_mes_pos; 
                    }
                    $("#text").val('');
                }
            }
        );
    }

    function messages_listener() {
    	$.get('{% url 'snn:messages_giver' %}',{user_id:user_id, mes_id:last_rec_mes_id}, 
        	function(data, status){
                if (status=="success") {
                	var messages = JSON.parse(data);
                	var last_index = messages.length;
        			last_rec_mes_id = messages[last_index-1].message_id;
        			messages.forEach(display_message);
                }
            }
        );
    }
     
    setInterval(messages_listener, 3000);
    setInterval(form_chats, 3000);
</script>
</html>

snn/templates/snn/profile_page.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>{{username}} profile page</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" charset="UTF-8">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'snn/css/profile_page.css' %}" />
</head>
<body>
	<header>
		<nav class="navbar navbar-default navbar-fixed-top" style="background: linear-gradient(to bottom, #33ccff 0%, #ff99cc 100%); height: 5%;">
		    <div class="container-fluid">
			    <div class="navbar-header">
				    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
					    <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span> 
					</button>
					<a class="navbar-brand" href="{% url 'snn:profile_page' user_id %}">{{username}}</a>
				</div>
				<div class="collapse navbar-collapse" id="myNavbar">
					<ul class="nav navbar-nav navbar-right">
					    <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
    <div class="container-fluid" style="margin-top:50px">
    	<div class="row">
    		<div class="col-sm-4">
    			<div><h1>Your friends</h1></div>
    			<div id="chat" style="text-align:center">
    				{% if not fr_info %}
    				    You have no friends! 
    				    In Social Nano Network you can send messages only to friends. So first add some friends <strong>&#x21E8;</strong> 
    				{% else %}
    				    {% for fr in fr_info %}
    				        <form method="post" action="{% url 'snn:chat_room' user_id %}">
    				        	{% csrf_token %}
                                <div><strong>{{fr.name}}</strong></div>
                                <input type="hidden" name="fr_id" value="{{fr.id}}">
                                <input type="hidden" name="fr_name" value="{{fr.name}}">
                                <input type="submit" value="Go and chat with {{fr.name}}" class="btn btn-primary">
    				        </form>
    				        <br>
    			        {% endfor %}
    				{% endif %}
    			</div>
    		</div>
    		<div class="col-sm-5">
    			<div><h1>List of network members</h1></div>
    			<div id="inventory" style="text-align:center">
    				{% for member in members %}
    				    <form method="post" action="{% url 'snn:add_remove_friends' user_id %}">
    				    	{% csrf_token %}
    				    	<div><strong>{{member.username}}</strong></div>
    				    	<input type="hidden" name="member_id" value="{{member.user_id}}">
    				    	{% if not member.user_id in fr_IDs %}
    				    	    <input type="hidden" name="action" value="add">
                                <input type="submit" value="Add to friends" class="btn btn-primary">
    				    	{% else %}
    				    	    <input type="hidden" name="action" value="remove">
    				    	    <input type="submit" value="Remove from friends" class="btn btn-primary">
    				    	{% endif %}
    				    </form>
    				    <br>
    				{% endfor %}
    			</div>
    		</div>
    		<div class="col-sm-3">
                <div><h1>Advertisments</h1></div>
                <div id="money" style="text-align: center;">
                    Your advertisment could be here. Hurry up, because soon Social Nano Network will become so popular! 
                </div>
           </div> 
    	</div>
    </div>
</body>
<script type="text/javascript">
	var last_friendship_id = {{last_friendship_id}}
	function catch_friends() {
		$.get('{% url 'snn:catch_friends' %}',{user_id:{{user_id}}, id:last_friendship_id}, 
			function(data, status){
                if (status=="success") {
                	var last_friendship_id_update = data;
                	if (last_friendship_id_update > last_friendship_id) {
                		last_friendship_id = last_friendship_id_update;
                		alert("Congratulations! Someone has just added you to their friend list!")
                		location.reload();
                	} else {
                		last_friendship_id = last_friendship_id_update;
                		alert("So sad... Someone has just removed you from their friend list...")
                		location.reload();
                	}
                }
            }
        );
	}
	setInterval(catch_friends, 3000);
</script>
</html>